const GET_CATALOGS = 'GET_CATALOGS';
const GET_CATALOGS_RECEIVED = 'GET_CATALOGS_RECEIVED';
const REFRESH_GET_CATALOGS = 'REFRESH_GET_CATALOGS';

export {
	GET_CATALOGS,
	GET_CATALOGS_RECEIVED,
	REFRESH_GET_CATALOGS
};
